#!/usr/bin/python
# -*- coding: UTF-8 -*-
# vim:set shiftwidth=4 tabstop=4 expandtab textwidth=79:
# Author: Shellex Wai <5h3ll3x@gmail.com>
# License: GNU LGPL
# Last modified:

"""
"""
__revision__ = '0.1'

if __name__=="__main__":
    import hotot.hotot
    hotot.hotot.main()



